name: Auto Update Templates

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Update Templates
        run: |
          chmod +x .gitea/scripts/update_templates.sh
          ./.gitea/scripts/update_templates.sh

      - name: Commit and Push
        run: |
          git config user.name "Wizzard"
          git config user.email "rich@bandaholics.cash"
          git add */template
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update templates [skip ci]"
            git pull --rebase origin "$(git rev-parse --abbrev-ref HEAD)"
            git push
          else
            echo "No template changes"
          fi
